ktor:
    application:
        modules:
            - com.adapp.backend.ApplicationKt.module
    deployment:
        port: 8081
        # Configuraci√≥n para soportar archivos grandes (audio)
        maxRequestSize: 52428800  # 50 MB en bytes
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
postgres:
  url: "jdbc:postgresql://3.214.47.23:5432/adapp"
  driver: "org.postgresql.Driver"
  user: "admin_adapp"
  password: "Xy9#mP2!oLq"
  maxPoolSize: 10
